class Tecnologias {
  static const DISENIO_E_INTEGRACION_DE_AUTOMATISMOS_MECATRONICOS =
      'DISEÑO E INTEGRACIÓN DE AUTOMATISMOS MECATRÓNICOS';
  static const CONSTRUCCION = 'CONSTRUCCIÓN';
  static const MANTENIMIENTO_MECANICO_INDUSTRIAL =
      'MANTENIMIENTO MECÁNICO INDUSTRIAL';
  static const MANTENIMIENTO_ELECTROMECANICO_INDUSTRIAL =
      'MANTENIMIENTO ELECTROMECÁNICO INDUSTRIAL';
  static const MANTENIMIENTO_ELECTRONICO_E_INSTRUMENTAL_INDUSTRIAL =
      'MANTENIMIENTO ELECTRÓNICO E INSTRUMENTAL INDUSTRIAL';
  static const MANTENIMIENTO_MECATRONICO_DE_AUTOMOTORES =
      'MANTENIMIENTO MECATRÓNICO DE AUTOMOTORES';
  static const FABRICACION_DE_MOLDES_Y_TROQUELES =
      'FABRICACIÓN DE MOLDES Y TROQUELES';
  static const ELECTRICIDAD_INDUSTRIAL = 'ELECTRICIDAD INDUSTRIAL';
  static const GESTION_INTEGRADA_DE_LA_CALIDAD_MEDIO_AMBIENTE_SEGURIDAD_Y_SALUD_OCUPACIONAL =
      'GESTIÓN INTEGRADA DE LA CALIDAD, MEDIO AMBIENTE, SEGURIDAD Y SALUD OCUPACIONAL';
  static const CONFECCION_INDUSTRIAL = 'CONFECCIÓN INDUSTRIAL';
  static const GESTION__DE_EMPRESAS_AGROPECUARIAS =
      'GESTIÓN  DE EMPRESAS AGROPECUARIAS';
  static const PRODUCCION_GANADERA = 'PRODUCCIÓN GANADERA';
  static const CONTROL_DE_CALIDAD_DE_ALIMENTOS =
      'CONTROL DE CALIDAD DE ALIMENTOS';
  static const PROCESAMIENTO_DE_ALIMENTOS = 'PROCESAMIENTO DE ALIMENTOS';
  static const GESTION_DE_RECURSOS_NATURALES = 'GESTIÓN DE RECURSOS NATURALES';
  static const PRODUCCION_AGROPECUARIA_ECOLOGICA =
      'PRODUCCIÓN AGROPECUARIA ECOLÓGICA';
  static const ANIMACION_DIGITAL = 'ANIMACIÓN DIGITAL';
  static const PRODUCCION_DE_MULTIMEDIA = 'PRODUCCIÓN DE MULTIMEDIA';
  static const ANALISIS_Y_DESARROLLO_DE_SISTEMAS_DE_INFORMACION =
      'ANÁLISIS Y DESARROLLO DE SISTEMAS DE INFORMACIÓN';
  static const PRODUCCION_DE_MEDIOS_AUDIOVISUALES_DIGITALES =
      'PRODUCCIÓN DE MEDIOS AUDIOVISUALES DIGITALES';
  static const IMPLEMENTACION_DE_INFRAESTRUCTURA_TIC =
      'IMPLEMENTACIÓN DE INFRAESTRUCTURA TIC';
  static const GESTION_DE_REDES_DE_DATOS = 'GESTIÓN DE REDES DE DATOS';
  static const ACTIVIDAD_FISICA = 'ACTIVIDAD FÍSICA';
  static const GUIANZA_TURISTICA = 'GUIANZA TURÍSTICA';
  static const BIOCOMERCIO_SOSTENIBLE = 'BIOCOMERCIO SOSTENIBLE';
  static const NEGOCIACION_INTERNACIONAL = 'NEGOCIACIÓN INTERNACIONAL';
  static const DIRECCION_DE_VENTAS = 'DIRECCIÓN DE VENTAS';
  static const COMUNICACION_COMERCIAL = 'COMUNICACIÓN COMERCIAL';
  static const GESTION__DE_MERCADOS = 'GESTIÓN  DE MERCADOS';
  static const GESTION_LOGISTICA = 'GESTIÓN LOGÍSTICA';
  static const GESTION_DE_PROYECTOS_DE_DESARROLLO_ECONOMICO_Y_SOCIAL =
      'GESTIÓN DE PROYECTOS DE DESARROLLO ECONÓMICO Y SOCIAL';
  static const GESTION_CONTABLE_Y_FINANCIERA = 'GESTIÓN CONTABLE Y FINANCIERA';
  static const GESTION_BANCARIA_Y_DE_ENTIDADES_FINANCIERAS =
      'GESTIÓN BANCARIA Y DE ENTIDADES FINANCIERAS';
  static const GESTION_ADMINISTRATIVA = 'GESTIÓN ADMINISTRATIVA';
  static const GESTION_DEL_TALENTO_HUMANO = 'GESTIÓN DEL TALENTO HUMANO';
  static const GESTION_DOCUMENTAL = 'GESTIÓN DOCUMENTAL';

  static const ALL_TECNOLOGIAS = [
    DISENIO_E_INTEGRACION_DE_AUTOMATISMOS_MECATRONICOS,
    CONSTRUCCION,
    MANTENIMIENTO_MECANICO_INDUSTRIAL,
    MANTENIMIENTO_ELECTROMECANICO_INDUSTRIAL,
    MANTENIMIENTO_ELECTRONICO_E_INSTRUMENTAL_INDUSTRIAL,
    MANTENIMIENTO_MECATRONICO_DE_AUTOMOTORES,
    FABRICACION_DE_MOLDES_Y_TROQUELES,
    ELECTRICIDAD_INDUSTRIAL,
    GESTION_INTEGRADA_DE_LA_CALIDAD_MEDIO_AMBIENTE_SEGURIDAD_Y_SALUD_OCUPACIONAL,
    CONFECCION_INDUSTRIAL,
    GESTION__DE_EMPRESAS_AGROPECUARIAS,
    PRODUCCION_GANADERA,
    CONTROL_DE_CALIDAD_DE_ALIMENTOS,
    PROCESAMIENTO_DE_ALIMENTOS,
    GESTION_DE_RECURSOS_NATURALES,
    PRODUCCION_AGROPECUARIA_ECOLOGICA,
    ANIMACION_DIGITAL,
    PRODUCCION_DE_MULTIMEDIA,
    ANALISIS_Y_DESARROLLO_DE_SISTEMAS_DE_INFORMACION,
    PRODUCCION_DE_MEDIOS_AUDIOVISUALES_DIGITALES,
    IMPLEMENTACION_DE_INFRAESTRUCTURA_TIC,
    GESTION_DE_REDES_DE_DATOS,
    ACTIVIDAD_FISICA,
    GUIANZA_TURISTICA,
    BIOCOMERCIO_SOSTENIBLE,
    NEGOCIACION_INTERNACIONAL,
    DIRECCION_DE_VENTAS,
    COMUNICACION_COMERCIAL,
    GESTION__DE_MERCADOS,
    GESTION_LOGISTICA,
    GESTION_DE_PROYECTOS_DE_DESARROLLO_ECONOMICO_Y_SOCIAL,
    GESTION_CONTABLE_Y_FINANCIERA,
    GESTION_BANCARIA_Y_DE_ENTIDADES_FINANCIERAS,
    GESTION_ADMINISTRATIVA,
    GESTION_DEL_TALENTO_HUMANO,
    GESTION_DOCUMENTAL,
  ];
}
